
#服务名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: 你的git服务器地址
          username: git账号
          password: 密码
          timeout: 5
          default-label: master
          search-paths: /**

server:
  port: 9100

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

