
#服务名称
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/HmanDemo/config-server.git
          username: 13265948041
          password: huangxiong123
          timeout: 5
          default-label: master
          search-paths: /**

server:
  port: 9100

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

